[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 1

remappings = [
    "@openzeppelin/=contracts/lib/openzeppelin-contracts/",
    "@pyth/=contracts/lib/pyth-sdk-solidity/",
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"
local = "http://127.0.0.1:8545"

[etherscan]
hedera_testnet = { key = "${HEDERA_API_KEY}", url = "https://testnet.hashscan.io/api" }
hedera_mainnet = { key = "${HEDERA_API_KEY}", url = "https://hashscan.io/api" }
